- hosts: localhost
#  become: yes
  roles:
     - osp-network
     - osp-keypair
     - osp-securitygroup
     - osp-flavor
  tasks:
##Create Fronend Instance
  - name: Create frontend instance
    include_role:
       name: osp-instances
       vars_from: frontend.yaml
###Create App1 server 
  - name: Create app1 instance
    include_role:
       name: osp-instances
       vars_from: app1.yaml
##Create App2 server
  - name: Create app2 instance
    include_role:
       name: osp-instances
       vars_from: app2.yaml
##Create DB server
  - name: Create db instance
    include_role:
       name: osp-instances
       vars_from: db.yaml
## Alternate Method to create dynmaic inventory
  - name: Gather facts
    include_role: 
       name: osp-facts
    tags:
     - test_inventory


- name: configure the App Servers
  hosts: apps
  #gather_facts: true
  become: true


  roles:
    - {name: enable-repos, tags: repos}
    - {name: app-servers, tags: apps}

- name: configure db server
  hosts: appdbs
  #gather_facts: false
  become: true


  roles:
  #  - {name: db-server, tags: dbs}
    - {name: enable-repos, tags: repos}
    - {name: geerlingguy.postgresql, tags: db}

- name: configure frontends
  hosts: frontends
  #gather_facts: false
  become: true
  
  roles:
    - {name: enable-repos, tags: repos}
    - {name: frontend, tags: frontends}
 #   - {name: geerlingguy.haproxy, tags: frontends}
