---
# tasks file for frontend
- name: install "{{ package }}" package
  yum:
    name: "{{ package }}"
    state: latest

- name: install "{{ h_package }}" package
  yum:
    name: "{{ h_package }}"
    state: latest

- name: start and enable "{{ h_package }}" daemon
  service:
    name: "{{ h_package }}"
    state: started
    enabled: true

- name: template out HAProxy configuration file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart haproxy
