---
# tasks file for frontend
- name: install apache package
  yum:
    name: httpd
    state: latest

- name: install HAProxy package
  yum:
    name: haproxy
    state: latest

- name: start and enable HAProxy daemon
  service:
    name: haproxy
    state: started
    enabled: true

- name: template out HAProxy configuration file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart haproxy
